# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sqlite' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sqlite

  pod 'SQLite.swift', '~> 0.11.3'

  target 'SqliteTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SqliteUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
